"""Unit tests for Paisa v0.7.4 diagnosis classification (contra-expense
``Debit Entry`` dangers the projection provably generates vs. everything else).

Covers the contract required by the live-sync integration:
* legitimate generated refund/cashback/fee-reversal ``Debit Entry`` dangers are
  *accepted* (downgraded) via exact ``(account, date, amount)`` fingerprint
  matching against the typed ProjectionReport;
* an extra same-account/date/amount danger beyond the expected multiplicity
  stays fatal;
* an unmatched ``Debit Entry`` (operator-authored content), any other expense
  debit not generated by us, a ``Negative Balance``, and a malformed/unparseable
  issue all stay fatal;
* matching is anchored on Paisa's real HTML template (no blanket string
  suppression) and the Go ``02 Jan 2006`` date format.
"""

import datetime
from collections import Counter
from decimal import Decimal

import pytest

from financial_dashboard.integrations.paisa import PaisaDiagnosis, PaisaDiagnosisIssue
from financial_dashboard.services.paisa.diagnosis import (
    DEBIT_ENTRY_SUMMARY,
    DebitEntryFingerprint,
    classify_diagnosis,
    expected_debit_entry_fingerprints,
    parse_debit_entry_details,
)
from financial_dashboard.services.paisa.renderers.base import (
    LedgerPosting,
    ProjectedEntry,
)

CUTOVER = datetime.date(2026, 1, 1)


# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------


def _entry(
    *,
    contra_account,
    contra_amount,
    date,
    kind="expense",
    bank_account="Assets:Bank:Hdfc:Savings",
    txn_ids=(1,),
):
    """A two-posting ProjectedEntry: bank leg + a contra (Expenses) leg.

    ``contra_amount`` is the *negative* contra posting (what Paisa's Debit Entry
    rule flags). The bank leg carries the equal-and-opposite positive amount so
    the entry is structurally balanced."""
    amount = Decimal(contra_amount)
    return ProjectedEntry(
        date=date,
        payee="Test",
        txn_ids=tuple(txn_ids),
        postings=(
            LedgerPosting(account=bank_account, amount=-amount),
            LedgerPosting(account=contra_account, amount=amount),
        ),
        kind=kind,
    )


def _debit_details(amount: str, account: str, date: datetime.date) -> str:
    """Render a details string in Paisa v0.7.4's exact ``ruleNonDebitAccount``
    template: ``<b>%.4f</b> got debited from <b>%s</b> on %s``."""
    amt = Decimal(amount).quantize(Decimal("0.0001"))
    return (
        f"<b>{amt:.4f}</b> got debited from <b>{account}</b> on "
        f"{date.strftime('%d %b %Y')}"
    )


def _diag(*issues: PaisaDiagnosisIssue) -> PaisaDiagnosis:
    danger = sum(1 for i in issues if i.level == "danger")
    warning = sum(1 for i in issues if i.level == "warning")
    first = next(
        ((i.summary or i.details) for i in issues if i.level == "danger"),
        None,
    )
    return PaisaDiagnosis(
        ok=danger == 0,
        danger_count=danger,
        warning_count=warning,
        issues=tuple(issues),
        first_message=first,
    )


def _danger(summary, details) -> PaisaDiagnosisIssue:
    return PaisaDiagnosisIssue(level="danger", summary=summary, details=details)


REFUND_DATE = datetime.date(2026, 2, 1)
CASHBACK_DATE = datetime.date(2026, 2, 2)
FEE_REV_DATE = datetime.date(2026, 2, 3)


# ---------------------------------------------------------------------------
# parse_debit_entry_details: real Paisa template
# ---------------------------------------------------------------------------


def test_parse_real_paisa_debit_entry_template():
    fp = parse_debit_entry_details(
        "<b>-236.0000</b> got debited from <b>Expenses:Fees Charges</b> on 15 Jan 2026"
    )
    assert fp == DebitEntryFingerprint(
        "Expenses:Fees Charges", datetime.date(2026, 1, 15), Decimal("-236.0000")
    )


def test_parse_handles_cashback_amount_and_spaces_in_account():
    fp = parse_debit_entry_details(
        "<b>-2916.1100</b> got debited from <b>Expenses:Cashback Rewards</b> on 02 Feb 2026"
    )
    assert fp.account == "Expenses:Cashback Rewards"
    assert fp.date == datetime.date(2026, 2, 2)
    assert fp.amount == Decimal("-2916.1100")


def test_parse_returns_none_for_non_matching_template():
    # A different danger kind's details, or a future upstream rewording, must
    # not half-match — the caller leaves the danger fatal.
    assert parse_debit_entry_details("Assets:Bank went negative") is None
    assert parse_debit_entry_details("") is None
    assert parse_debit_entry_details("garbage <b>not</b> a debit entry") is None
    assert (
        parse_debit_entry_details(
            "<b>-50.0000</b> posted to <b>Expenses:Refund</b>"  # wrong verb
        )
        is None
    )


def test_parse_returns_none_for_unparseable_amount_or_date():
    assert (
        parse_debit_entry_details(
            "<b>not-a-number</b> got debited from <b>Expenses:X</b> on 01 Feb 2026"
        )
        is None
    )
    assert (
        parse_debit_entry_details(
            "<b>-50.0000</b> got debited from <b>Expenses:X</b> on 99 Zzz 2026"
        )
        is None
    )


@pytest.mark.parametrize(
    "mon,expected",
    [
        ("Jan", 1),
        ("Feb", 2),
        ("Mar", 3),
        ("Apr", 4),
        ("May", 5),
        ("Jun", 6),
        ("Jul", 7),
        ("Aug", 8),
        ("Sep", 9),
        ("Oct", 10),
        ("Nov", 11),
        ("Dec", 12),
    ],
)
def test_parse_month_map_is_complete_and_locale_independent(mon, expected):
    """The month is parsed from a fixed English map (Go's ``time.Format`` always
    emits English), so a non-English server locale cannot mis-parse Paisa's
    date and turn an expected danger fatal."""
    fp = parse_debit_entry_details(
        f"<b>-50.0000</b> got debited from <b>Expenses:Refund</b> on 15 {mon} 2026"
    )
    assert fp is not None
    assert fp.date == datetime.date(2026, expected, 15)


# ---------------------------------------------------------------------------
# expected_debit_entry_fingerprints: derived from the typed report
# ---------------------------------------------------------------------------


def test_expected_fingerprints_collect_only_negative_expenses():
    entries = [
        _entry(
            contra_account="Expenses:Refund",
            contra_amount="-50.00",
            date=REFUND_DATE,
            kind="contra_expense",
        ),
        # A positive expense (normal spend) is NOT expected.
        _entry(
            contra_account="Expenses:Groceries",
            contra_amount="100.00",
            date=REFUND_DATE,
        ),
    ]
    fps = expected_debit_entry_fingerprints(entries)
    assert fps == Counter(
        [DebitEntryFingerprint("Expenses:Refund", REFUND_DATE, Decimal("-50.0000"))]
    )


def test_expected_fingerprints_are_multiplicity_aware():
    """Two identical refunds consume two fingerprints (not deduplicated)."""
    e = _entry(
        contra_account="Expenses:Refund",
        contra_amount="-50.00",
        date=REFUND_DATE,
        kind="contra_expense",
    )
    fps = expected_debit_entry_fingerprints([e, e])
    assert (
        fps[DebitEntryFingerprint("Expenses:Refund", REFUND_DATE, Decimal("-50.0000"))]
        == 2
    )


def test_expected_fingerprints_ignore_non_expenses_postings():
    # Card payments, self-transfers, openings post to liabilities/assets, never
    # to Expenses, so they contribute no expected Debit Entry danger.
    entry = ProjectedEntry(
        date=REFUND_DATE,
        payee="Card Payment",
        txn_ids=(1,),
        postings=(
            LedgerPosting("Liabilities:Card:Hdfc:Card", Decimal("5000.00")),
            LedgerPosting("Assets:Bank:Hdfc:Savings", Decimal("-5000.00")),
        ),
        kind="card_payment",
    )
    assert not expected_debit_entry_fingerprints([entry])


# ---------------------------------------------------------------------------
# classify_diagnosis: the contract
# ---------------------------------------------------------------------------


def test_refund_cashback_and_fee_reversal_are_accepted():
    """The headline case: legitimate generated contra-expense postings (refund,
    cashback, fee reversal) are all downgraded to accepted; sync succeeds."""
    entries = [
        _entry(
            contra_account="Expenses:Refund",
            contra_amount="-50.00",
            date=REFUND_DATE,
            kind="contra_expense",
        ),
        _entry(
            contra_account="Expenses:Cashback Rewards",
            contra_amount="-2916.11",
            date=CASHBACK_DATE,
            kind="contra_expense",
        ),
        _entry(
            contra_account="Expenses:Fees Charges",
            contra_amount="-236.00",
            date=FEE_REV_DATE,
            kind="expense",  # a fee reversal nets against the original fee
        ),
    ]
    diag = _diag(
        _danger(
            DEBIT_ENTRY_SUMMARY,
            _debit_details("-50.00", "Expenses:Refund", REFUND_DATE),
        ),
        _danger(
            DEBIT_ENTRY_SUMMARY,
            _debit_details("-2916.11", "Expenses:Cashback Rewards", CASHBACK_DATE),
        ),
        _danger(
            DEBIT_ENTRY_SUMMARY,
            _debit_details("-236.00", "Expenses:Fees Charges", FEE_REV_DATE),
        ),
    )
    c = classify_diagnosis(diag, entries)
    assert c.expected_count == 3
    assert c.accepted_count == 3
    assert c.fatal_count == 0
    assert c.first_fatal_message is None
    # raw_danger_count reflects what Paisa actually reported.
    assert c.raw_danger_count == 3


def test_extra_same_fingerprint_beyond_expected_multiplicity_is_fatal():
    """A third danger for a fingerprint expected twice is unmatched and fatal —
    multiplicity is exact, not set-membership."""
    e = _entry(
        contra_account="Expenses:Refund",
        contra_amount="-50.00",
        date=REFUND_DATE,
        kind="contra_expense",
    )
    # Only ONE expected, but Paisa reports two identical dangers.
    diag = _diag(
        _danger(
            DEBIT_ENTRY_SUMMARY,
            _debit_details("-50.00", "Expenses:Refund", REFUND_DATE),
        ),
        _danger(
            DEBIT_ENTRY_SUMMARY,
            _debit_details("-50.00", "Expenses:Refund", REFUND_DATE),
        ),
    )
    c = classify_diagnosis(diag, [e])
    assert c.expected_count == 1
    assert c.accepted_count == 1
    assert c.fatal_count == 1
    assert c.first_fatal_message is not None
    assert "Debit Entry" in c.first_fatal_message


def test_unmatched_debit_entry_from_operator_journal_is_fatal():
    """A Debit Entry whose fingerprint is NOT in the expected multiset (e.g. an
    operator-authored negative Expenses posting in their own include) stays
    fatal. It must never be blanket-suppressed."""
    diag = _diag(
        _danger(
            DEBIT_ENTRY_SUMMARY,
            _debit_details("-77.00", "Expenses:Hobbies", datetime.date(2026, 3, 1)),
        ),
    )
    c = classify_diagnosis(diag, [])
    assert c.accepted_count == 0
    assert c.fatal_count == 1


def test_negative_balance_is_always_fatal():
    """A Negative Balance danger is never classifiable — it stays fatal
    regardless of what the projection generated (the synth agent owns those)."""
    entries = [
        _entry(
            contra_account="Expenses:Refund",
            contra_amount="-50.00",
            date=REFUND_DATE,
            kind="contra_expense",
        )
    ]
    diag = _diag(
        _danger(
            DEBIT_ENTRY_SUMMARY,
            _debit_details("-50.00", "Expenses:Refund", REFUND_DATE),
        ),
        _danger(
            "Negative Balance",
            "<b>Assets:Bank:Hdfc:Savings</b> account went negative (-100.00) on 01 Feb 2026",
        ),
    )
    c = classify_diagnosis(diag, entries)
    assert c.accepted_count == 1
    assert c.fatal_count == 1
    # The fatal reason names the real problem (Negative Balance), not the
    # accepted contra-expense.
    assert "Negative Balance" in (c.first_fatal_message or "")


def test_malformed_debit_entry_is_fatal():
    """An unparseable Debit Entry (future upstream rewording) is not provably
    expected → fatal, never silently accepted."""
    entries = [
        _entry(
            contra_account="Expenses:Refund",
            contra_amount="-50.00",
            date=REFUND_DATE,
            kind="contra_expense",
        )
    ]
    diag = _diag(
        _danger(DEBIT_ENTRY_SUMMARY, "some new upstream message format"),
    )
    c = classify_diagnosis(diag, entries)
    assert c.accepted_count == 0
    assert c.fatal_count == 1


def test_warning_issues_never_affect_classification():
    """Warnings (Unit Price Mismatch, allocation gaps) are neither accepted nor
    fatal — they never affected sync and still do not."""
    entries = [
        _entry(
            contra_account="Expenses:Refund",
            contra_amount="-50.00",
            date=REFUND_DATE,
            kind="contra_expense",
        )
    ]
    diag = PaisaDiagnosis(
        ok=False,
        danger_count=1,
        warning_count=2,
        issues=(
            PaisaDiagnosisIssue(
                level="warning", summary="Unit Price Mismatch", details="..."
            ),
            _danger(
                DEBIT_ENTRY_SUMMARY,
                _debit_details("-50.00", "Expenses:Refund", REFUND_DATE),
            ),
            PaisaDiagnosisIssue(
                level="warning",
                summary="Asset Accounts missing from Allocation Target",
                details="...",
            ),
        ),
        first_message="Debit Entry",
    )
    c = classify_diagnosis(diag, entries)
    assert c.accepted_count == 1
    assert c.fatal_count == 0


def test_other_danger_kinds_are_fatal():
    """Credit Entry and Exchange Price Missing are real problems; never
    accepted even when we generated contra-expense postings."""
    entries = [
        _entry(
            contra_account="Expenses:Refund",
            contra_amount="-50.00",
            date=REFUND_DATE,
            kind="contra_expense",
        )
    ]
    diag = _diag(
        _danger(
            DEBIT_ENTRY_SUMMARY,
            _debit_details("-50.00", "Expenses:Refund", REFUND_DATE),
        ),
        _danger(
            "Credit Entry",
            "<b>100.0000</b> got credited to <b>Income:Salary</b> on 01 Feb 2026",
        ),
        _danger("Exchange Price Missing", "Exchange price ... is not specified"),
    )
    c = classify_diagnosis(diag, entries)
    assert c.accepted_count == 1
    assert c.fatal_count == 2


def test_clean_diagnosis_with_no_dangers():
    c = classify_diagnosis(
        PaisaDiagnosis(True, 0, 0, (), None),
        [
            _entry(
                contra_account="Expenses:Groceries",
                contra_amount="100.00",
                date=REFUND_DATE,
            )
        ],
    )
    # A positive expense generates no expected Debit Entry; clean diagnosis.
    assert c.expected_count == 0
    assert c.accepted_count == 0
    assert c.fatal_count == 0


def test_first_fatal_message_strips_html_and_includes_detail():
    """The reason message is HTML-stripped and bounded, so Paisa's ``<b>`` tags
    never reach the sync reason / audit error."""
    entries = []  # nothing expected → the Debit Entry is fatal
    diag = _diag(
        _danger(
            DEBIT_ENTRY_SUMMARY,
            _debit_details("-77.00", "Expenses:Hobbies", datetime.date(2026, 3, 1)),
        ),
    )
    c = classify_diagnosis(diag, entries)
    msg = c.first_fatal_message
    assert "<" not in msg
    assert ">" not in msg
    assert "Expenses:Hobbies" in msg
    assert "Debit Entry" in msg
