"""Atomic publisher for the single generated Paisa journal include file.

The publisher writes **only** the configured generated include — never the main
journal or the Paisa config. Paisa's own config file references this include
once (an operator sets that up); from then on every refresh rewrites the same
file atomically.

Atomicity & idempotency:

* The new bytes are written to a tempfile in the same directory as the target,
  fsync'd, then ``os.replace``'d into place. ``os.replace`` is atomic on POSIX,
  so a reader (Paisa reloading on sync) never sees a half-written file.
* If the new bytes are byte-identical to what is already on disk, the write is
  skipped entirely — no mtime churn, no redundant Paisa reload, and a stable
  hash the operator can audit.
* The directory containing the file is fsync'd after the replace so a crash
  leaves either the old file or the new file, not a renamed-away tempfile.

Path safety: the target must be absolute, must not traverse with ``..``, and
its parent directory must already exist. The publisher does not create
directories — silently materializing a tree on a typo'd path is the kind of
surprise a financial file should not allow.
"""

import hashlib
import os
import tempfile
from pathlib import Path
from typing import NamedTuple

from financial_dashboard.services.paisa.config import GENERATED_HEADER_VERSION

#: The header prefix lines every generated file carries, so a human opening it
#: knows it is regenerated and where the source of truth lives. The version is
#: the projection schema version (bumped on a breaking render change); the hash
#: is the SHA-256 of the body, so an operator can verify the file matches the
#: projection that produced it.
HEADER_LINES = (
    "; DO NOT EDIT — generated by financial-dashboard Paisa projection.",
    "; This file is overwritten on every generate/sync. Changes are lost.",
    f"; version: {GENERATED_HEADER_VERSION}",
)


class PublishError(Exception):
    """Raised when the target path is unsafe or unwritable."""


class PublishResult(NamedTuple):
    published: bool
    path: str
    version: str
    body_hash: str
    bytes_written: int

    @property
    def skipped(self) -> bool:
        return not self.published


def _check_path(path: str) -> Path:
    if not path or not path.strip():
        raise PublishError("Paisa generated_path is not configured.")
    target = Path(path).expanduser()
    if not target.is_absolute():
        raise PublishError(f"Paisa generated_path must be absolute, got {path!r}.")
    # Inspect the raw path for dot-segments BEFORE resolve() collapses them — a
    # resolved path never keeps '..', so the check is only meaningful on the
    # as-written form. A legitimate absolute path has no '..' segment.
    if ".." in target.parts:
        raise PublishError(f"Paisa generated_path must not traverse: {path!r}.")
    parent = target.parent
    if not parent.exists() or not parent.is_dir():
        raise PublishError(
            f"Paisa generated_path parent directory does not exist: {parent!r}."
        )
    return target


def _compose(body: str) -> tuple[bytes, str]:
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    header = "\n".join(HEADER_LINES) + f"\n; hash: {digest}\n\n"
    return (header + body).encode("utf-8"), digest


def _fsync_dir(path: Path) -> None:
    """Best-effort fsync of the directory holding a published file.

    Linux directory fsync is what durably commits a rename; on platforms
    without it (or where the dir is unopenable), we swallow the error — the
    atomic rename still holds in-memory and the next sync rewrites anyway.
    """
    try:
        fd = os.open(str(path), os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(fd)
    except OSError:
        pass
    finally:
        os.close(fd)


def publish_journal(path: str, body: str) -> PublishResult:
    """Atomically publish ``body`` to ``path``.

    Returns a :class:`PublishResult` describing what happened. A result with
    ``published=False`` means the on-disk bytes already matched and no write
    was performed — the common, idempotent case.
    """
    target = _check_path(path)
    data, digest = _compose(body)

    if target.exists():
        try:
            existing = target.read_bytes()
        except OSError as exc:
            raise PublishError(f"Could not read existing {target!r}: {exc}") from exc
        if existing == data:
            return PublishResult(
                published=False,
                path=str(target),
                version=GENERATED_HEADER_VERSION,
                body_hash=digest,
                bytes_written=len(existing),
            )

    parent = target.parent
    # Named tempfile in the SAME directory so os.replace stays atomic on one
    # filesystem. delete=False because we rename it ourselves.
    fd, tmp_name = tempfile.mkstemp(
        prefix=f".{target.name}.", suffix=".tmp", dir=str(parent)
    )
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, target)
        _fsync_dir(parent)
    except OSError:
        # Clean up the orphaned tempfile on any failure; the original file, if
        # any, is untouched because os.replace never ran.
        try:
            tmp_path.unlink()
        except OSError:
            pass
        raise
    return PublishResult(
        published=True,
        path=str(target),
        version=GENERATED_HEADER_VERSION,
        body_hash=digest,
        bytes_written=len(data),
    )
